### ISSUE TITLE
好像还是会有报错

### ISSUE THREAD

**Issue by ChenZIDu** [ccc-f/FEmailAll#1]
![image](https://user-images.githubusercontent.com/49174343/208580367-875e7177-c7af-4922-bae0-da07f6cb11d0.png)

**Comment by ccc-f** [comment]
![图片](https://user-images.githubusercontent.com/76417390/208583319-638f031e-a444-4e37-b1b6-31596e2445c7.png)
检查一下你的网络有没有问题，我刚刚克隆下来到Linux里跑了一遍没有问题。

**Comment by ChenZIDu** [comment]
那可能是windows的问题，我拉linux试试

**Comment by ChenZIDu** [comment]
没有安装pip3 install -U fake_useragent依赖，已经解决了
